### ISSUE TITLE
Provide way to automatically log in for demo purposes

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker-frontend#109]
Modify frontend so that you can specify username and it will log you in automatically.

<server>`/scan/1234?username=FED-ADMIN` would automatically log in with username FED-ADMIN, password FED-ADMIN-1010.
Other users would add `-1010` as pw

For demo purposes, could book mark:

<server>`/refresh` would set order 1 back to the beginning status - we don't need to demo creating one since when integrated, this will be part of the flow.  This would work best if backend code did the refreshing.  Alternatively, <server>`/refresh` could set all back to the original status
<server>`?username=FED-HOSS` would automatically log in as FED-HOSS
<server>`/scan/<predefined id>?username=FED-HOSS`
<server>`/scan/<predefined id>?username=FED-AOC`
etc...

**Comment by thadk** [comment]
I have clarified/suggested that the `?username=` query parameter work on any frontend route and that it will fully logout the previous user and login the specified `*-1010` user/password.

**Comment by thadk** [comment]
I also note, using the scheme above, we could even encode this demo URL into a QR Code to scan for demo as we had planned, as long as we stick to the password pattern for now.

**Comment by thadk** [comment]
I think `/refresh` is a backend API, not a frontend one, so maybe we should make it`/api/refresh` instead?
