### ISSUE TITLE
Improve search/sort UI

### ISSUE THREAD

**Issue by rkaufman13** [codefordc/us-congress-pizza-flag-tracker-frontend#117]
As I'm looking at this screenshot (currently only running locally on my machine but maybe soon to be pushed to prod) I'm thinking that some of the advanced search options (state, office, etc) are taking up too much space, and the sort buttons are taking up not enough space--it's not obvious that you can click the words "sort by" to bring up a bunch of sort options.

I also think now that we have moved away from a tabular data format, having sort options in columns makes less sense. Maybe there's a different way we can present the options other than in one row.

![Screen Shot 2022-05-29 at 12 10 01 PM](https://user-images.githubusercontent.com/16939591/170879786-a7824d3b-4eb5-4452-a11e-51ddc8f03c12.png)

**Comment by rkaufman13** [comment]
Step 1: @pekingPow will look into changing the link Sort By into a more visible button
(Juan: look in src/components/tableHeader.js)

**Comment by mertbagt** [comment]
folded into Issue https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/issues/162
#162 opened 22 days ago by [rkaufman13](https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/issues?q=is%3Aissue+is%3Aopen+author%3Arkaufman13)
