### ISSUE TITLE
Log out if token is stale

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker-frontend#121]
To reproduce:

- In .env file, set refresh to 1 second and expire to 5 seconds
```
   TOKEN_EXPIRE_DAYS = 0.00005
   TOKEN_REFRESH_AFTER_DAYS = 0.00001 
```
- Launch app
- Log out if logged in
- Execute a filter
- Should work if within 5 seconds
- Wait 5 seconds
- Execute a filter
- Should fail

How to fix:
- Modify refreshTokenWrapperFunction or where it is called to go to log in screen

**Comment by mertbagt** [comment]
addressed with frontend PR: expired token handling #180
