### ISSUE TITLE
Hide search form and sort options if no data exists

### ISSUE THREAD

**Issue by rkaufman13** [codefordc/us-congress-pizza-flag-tracker-frontend#137]
![Screen Shot 2022-06-29 at 7 55 47 PM](https://user-images.githubusercontent.com/16939591/176564933-c18d59d4-6f48-4f3a-983d-c60e0a25c619.png)

None of this should be displayed if no data exists.

**Comment by yaki3355** [comment]
Hey @rkaufman13 
I got 'Merging is blocked' for my pr to main branch.
Should I make a pr to another branch?
