### ISSUE TITLE
Delete order error

### ISSUE THREAD

**Issue by mertbagt** [codefordc/us-congress-pizza-flag-tracker-frontend#163]
thad: Maybe rather than actually deleting the order, let's add a column which indicates the order is archived/hidden and respect that around the app.

If we completely delete orders, then we run into problems with the logs because of constraints about continuing to reference non-existent rows. 

![image](https://user-images.githubusercontent.com/73559781/182183877-511dc20c-80da-4041-af2c-8d77180b299c.png)

**Comment by mertbagt** [comment]
This doesn't occur on local instances
but does seems to occur on deploy previews and codefordc-flag.netlify.app/

possibly sqlite vs postgres ?

**Comment by rkaufman13** [comment]
@Tmstone can you look into adding some sort of `on delete cascade` for postgres?

**Comment by thadk** [comment]
Maybe rather than actually deleting the order, let's add a column which indicates the order is archived/hidden and respect that around the app.

**Comment by thadk** [comment]
suggesting this for livecoding with @ethanstrominger next time he's around on a Wednesday.
