### ISSUE TITLE
Filter by order_number, office code. and any other displayed field

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker-frontend#38]
Currently, it only filters by order_number.  Options:
1. Maybe there is a react widget that can filter a list?
2. Create a new state filtered_orders.  On the front end use JavaScript to filter the list.
3. Create a new route backend route for filtering by any field and a corresponding route.

**Comment by rkaufman13** [comment]
I've used react-table in other projects for filtering data, but its documentation is terrible. I'm happy to research some other options.
