### ISSUE TITLE
Revert status should revert status based on log

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker-frontend#91]

**Comment by ethanstrominger** [comment]
Revert status should revert to the status that the order was previously set to.  It currently looks at the previous status in the status list?

**Comment by ethanstrominger** [comment]
This can call the Revert Status route once that is created.

**Comment by mertbagt** [comment]
> Revert status should revert to the status that the order was previously set to. It currently looks at the previous status in the status list?

Revert does not look at the previous status in the the Status list.

When you first get to the Scan Page, both order and oldOrder get set to initialOrderState as passed down by the props.

When you update, order gets set to the use the nextStatus, but oldOrder remains unchanged.

When you revert, order gets set to oldOrder, that is the initialOrderState.  Effectively you're rewinding to the specific state you were in *before* you attempted to update.

Thinking about it, I could get rid of the oldOrder state and just use initialOrderState directly if that's clearer/more obvious.

**Comment by mertbagt** [comment]
It seens to me, using the log here is recalculating information that you already have.

**Comment by mertbagt** [comment]
possibly rename oldOrder to originalOrder or unmodifiedOrder?
